export type GameCategory = "slot" | "cards" | "fishing";

export type SlotGame = {
  id: string;
  name: string;
  provider: string;
  thumb: string;
  category: GameCategory;
  tag?: string;
  description: string;
  rating: number;
  reviews: number;
  rtp: string;
  volatility: "Low" | "Medium" | "High" | "Very High";
  maxWin: string;
  minBet: string;
  maxBet: string;
  features: string[];
};

const defaults = {
  provider: "MaxHigh",
  rating: 4.6,
  reviews: 1280,
  rtp: "96.5%",
  volatility: "Medium" as const,
  maxWin: "5,000x",
  minBet: "₱0.20",
  maxBet: "₱100",
  features: ["Free Spins", "Multipliers", "Wilds"],
};

/** MaxHigh original titles with thumbnail art */
export const slotGames: SlotGame[] = [
  {
    ...defaults,
    id: "mahjong-ways",
    name: "Mahjong Ways",
    thumb: "/games/mahjong-ways.webp",
    category: "slot",
    tag: "Hot",
    description: "Experience the thrilling Chinese tile slot with dynamic Left-to-Right ways, cascading tumble drops, transforming Gold Wilds, and progressive win multipliers!",
    rating: 5.0,
    reviews: 1420,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "25,000x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["Dynamic Ways", "Cascading Tumble", "Gold Wild Transform", "Progressive Multiplier", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "mahjong-ways-2",
    name: "Mahjong Ways 2",
    thumb: "/games/mahjong-ways-2.webp",
    category: "slot",
    tag: "New",
    description:
      "The sequel returns with 5×4 ways, cascading tumble drops, gold wild transforms, and progressive cascade multipliers — plus free spins and buy bonus.",
    rating: 5.0,
    reviews: 980,
    rtp: "96.9%",
    volatility: "High",
    maxWin: "2,893x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["Dynamic Ways", "Cascading Tumble", "Gold Wild Transform", "Progressive Multiplier", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "dragon-phoenix",
    name: "Dragon & Phoenix",
    thumb: "/games/dragon-phoenix.webp",
    category: "slot",
    tag: "New",
    description:
      "Mythic 5×4 ways with cascading tumble drops, gold wild transforms, and progressive cascade multipliers — free spins and buy bonus included.",
    rating: 5.0,
    reviews: 860,
    rtp: "96.9%",
    volatility: "High",
    maxWin: "2,893x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["Dynamic Ways", "Cascading Tumble", "Gold Wild Transform", "Progressive Multiplier", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "chinese-new-year",
    name: "Chinese New Year",
    thumb: "/games/chinese-new-year.webp",
    category: "slot",
    tag: "Hot",
    description:
      "Gong Xi Fa Cai! 5×3 fixed paylines with Dragon Fireworks, Monkey Free Spins, Extra Scatter wheel, and optional Gamble.",
    rating: 5.0,
    reviews: 820,
    rtp: "96.02%",
    volatility: "Med-High",
    maxWin: "12,000x",
    minBet: "₱0.50",
    maxBet: "₱600",
    features: [
      "20 Paylines",
      "Dragon Fireworks",
      "Monkey Free Spins",
      "Extra Scatter",
      "Gamble",
    ],
  },
  {
    ...defaults,
    id: "fiesta-fireworks",
    name: "Fiesta Fireworks",
    thumb: "/games/fiesta-fireworks.webp",
    category: "slot",
    tag: "New",
    description:
      "Fiesta night fireworks! 5×3 fixed paylines with Dragon Fireworks, Monkey Free Spins, Extra Scatter wheel, and optional Gamble.",
    rating: 5.0,
    reviews: 640,
    rtp: "96.02%",
    volatility: "High",
    maxWin: "12,000x",
    minBet: "₱0.50",
    maxBet: "₱600",
    features: [
      "20 Paylines",
      "Dragon Fireworks",
      "Monkey Free Spins",
      "Extra Scatter",
      "Gamble",
    ],
  },
  {
    ...defaults,
    id: "golden-panther",
    name: "Golden Panther",
    thumb: "/images/thumbnails/panther_thumb.png",
    category: "slot",
    tag: "New",
    description: "Explore the golden jungle temple and uncover the majestic Golden Panther's hidden treasures with cascading wins and multipliers.",
    rating: 4.9,
    reviews: 512,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "10,000x",
    minBet: "₱0.20",
    maxBet: "₱200",
    features: ["Cascading Wins", "Free Spins", "Buy Bonus", "Multipliers"],
  },
  {
    ...defaults,
    id: "aztec-treasure",
    name: "Aztec Treasure",
    thumb: "/games/aztec-treasure.webp",
    category: "slot",
    tag: "New",
    description:
      "Raid an ancient Aztec temple for cascading cluster wins, bomb multipliers, ante bets, and free-spin treasure hunts.",
    rating: 4.9,
    reviews: 420,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "10,000x",
    minBet: "₱0.20",
    maxBet: "₱200",
    features: ["Cascading Wins", "Free Spins", "Buy Bonus", "Multipliers", "Ante Bet"],
  },
  {
    ...defaults,
    id: "pirate-plunder",
    name: "Pirate Plunder",
    thumb: "/games/pirate-plunder.webp",
    category: "slot",
    tag: "New",
    description:
      "Sail for cascading cluster wins, bomb multipliers, ante bets, and free-spin treasure hunts on the high seas.",
    rating: 4.9,
    reviews: 390,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "10,000x",
    minBet: "₱0.20",
    maxBet: "₱200",
    features: ["Cascading Wins", "Free Spins", "Buy Bonus", "Multipliers", "Ante Bet"],
  },
  {
    ...defaults,
    id: "candy-peak",
    name: "Candy Peak",
    thumb: "/games/candy-peak.webp",
    category: "slot",
    tag: "Hot",
    description:
      "Climb the sugar mountain in Candy Peak — a colorful MaxHigh original packed with cascading wins, sticky sweets, and a progressive Peak Bonus. Match candy clusters, unlock free spins, and chase the Super Peak jackpot.",
    rating: 4.9,
    reviews: 4821,
    rtp: "96.8%",
    volatility: "High",
    maxWin: "12,500x",
    minBet: "₱0.10",
    maxBet: "₱250",
    features: ["Cascading Wins", "Peak Bonus", "Sticky Wilds", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "mermaid-riches",
    name: "Mermaid Riches",
    thumb: "/games/mermaid-riches.webp",
    category: "slot",
    tag: "New",
    description:
      "Dive into cascading candy-style cluster wins under the sea — sticky sweets, progressive Peak Bonus, free spins, and buy feature.",
    rating: 4.9,
    reviews: 2100,
    rtp: "96.8%",
    volatility: "High",
    maxWin: "12,500x",
    minBet: "₱0.10",
    maxBet: "₱250",
    features: ["Cascading Wins", "Peak Bonus", "Sticky Wilds", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "godly-gates",
    name: "Godly Gates",
    thumb: "/games/godly-gates.webp",
    category: "slot",
    tag: "New",
    description:
      "Enter the temple of thunder. Godly Gates rains multipliers from the sky — hit the sacred gates for divine free spins and lightning payouts.",
    rating: 4.8,
    reviews: 2104,
    rtp: "96.4%",
    volatility: "Very High",
    maxWin: "15,000x",
    features: ["Cascading Wins", "Ways", "Free Spins", "Buy Bonus", "Progressive Mult"],
  },
  {
    ...defaults,
    id: "olympus-wrath",
    name: "Olympus Wrath",
    thumb: "/games/olympus-wrath.webp",
    category: "slot",
    tag: "Hot",
    provider: "MaxHigh",
    description:
      "Zeus rains multipliers from the sky. Cascade ways, divine free spins, and buy-feature thunder — Godly Gates math in Olympian wrath skin.",
    rating: 4.8,
    reviews: 2400,
    rtp: "96.4%",
    volatility: "Very High",
    maxWin: "15,000x",
    features: ["Cascading Wins", "Ways", "Free Spins", "Buy Bonus", "Progressive Mult"],
  },
  {
    ...defaults,
    id: "enchanted-grove",
    name: "Enchanted Grove",
    thumb: "/games/enchanted-grove.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Mystical grove cascades with ways wins, progressive multipliers, free spins, and buy-feature magic — Godly Gates math in enchanted skin.",
    rating: 4.8,
    reviews: 2100,
    rtp: "96.4%",
    volatility: "Very High",
    maxWin: "15,000x",
    features: ["Cascading Wins", "Ways", "Free Spins", "Buy Bonus", "Progressive Mult"],
  },
  {
    ...defaults,
    id: "sugar-surge",
    name: "Sugar Surge",
    thumb: "/games/sugar-surge.webp",
    category: "slot",
    tag: "Hot",
    description:
      "A sugar rush of tumbling wins. Fill the gumball meter to trigger Surge Mode and explode the reels with candy chaos.",
    rating: 4.7,
    reviews: 3560,
    volatility: "Medium",
    maxWin: "8,000x",
    features: ["Tumble Wins", "Surge Meter", "Free Spins", "Wild Multipliers"],
  },
  {
    ...defaults,
    id: "boracay-bounce",
    name: "Boracay Bounce",
    thumb: "/games/boracay-bounce.webp",
    category: "slot",
    tag: "New",
    description:
      "Island candy cascades on Boracay. Cluster tumbles, bounce multipliers, free spins, and buy-feature beach chaos.",
    rating: 4.7,
    reviews: 2100,
    volatility: "Medium",
    maxWin: "8,000x",
    features: ["Tumble Wins", "Cluster Pays", "Free Spins", "Wild Multipliers"],
  },
  {
    ...defaults,
    id: "starlight-ace",
    name: "Starlight Ace",
    thumb: "/games/starlight-ace.webp",
    category: "slot",
    tag: "New",
    description:
      "5×5 ways cascade with Golden→Wild transforms, climbing multipliers, and Free Spins with a Guaranteed Golden Reel.",
    rating: 4.7,
    reviews: 1890,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "100,000x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["3,125 Ways", "Golden→Wild", "Cascade Mult", "FS Golden Reel", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "manila-nights",
    name: "Manila Nights",
    thumb: "/games/manila-nights.webp",
    category: "slot",
    tag: "New",
    description:
      "Neon Manila skyline cascade: 5×5 ways with Golden→Wild transforms, climbing multipliers, and Free Spins with a Guaranteed Golden Reel.",
    rating: 4.7,
    reviews: 1560,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "100,000x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["3,125 Ways", "Golden→Wild", "Cascade Mult", "FS Golden Reel", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "deep-bass",
    name: "Deep Bass",
    provider: "MaxHigh",
    thumb: "/games/deep-bass.webp",
    category: "fishing",
    tag: "New",
    description:
      "Dive deep and land the legendary bass. Arcade fishing action with boss fish, multipliers, and coin rain rewards.",
    rating: 4.5,
    reviews: 980,
    rtp: "96.00%",
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱25",
    features: ["Boss Fish", "Multi-Catch", "Coin Rain", "Power Cannons"],
  },
  {
    ...defaults,
    id: "dragon-fisher",
    name: "Dragon Fisher",
    provider: "MaxHigh",
    thumb: "/games/dragon-fisher.webp",
    category: "fishing",
    tag: "New",
    description:
      "Hunt mythical sea dragons in arcade fishing combat. Boss fights, power weapons, and coin-rain payouts.",
    rating: 4.5,
    reviews: 920,
    rtp: "96.00%",
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱25",
    features: ["Boss Fish", "Multi-Catch", "Coin Rain", "Power Cannons"],
  },
  {
    ...defaults,
    id: "crab-cannon",
    name: "Crab Cannon",
    provider: "MaxHigh",
    thumb: "/games/crab-cannon.webp",
    category: "fishing",
    tag: "New",
    description:
      "Blast crustacean swarms with heavy cannons. Arcade fishing with boss crabs, net bombs, and coin rain.",
    rating: 4.4,
    reviews: 860,
    rtp: "96.00%",
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱25",
    features: ["Boss Fish", "Multi-Catch", "Coin Rain", "Power Cannons"],
  },
  {
    ...defaults,
    id: "phoenix-fisher",
    name: "Phoenix Fisher",
    provider: "MaxHigh",
    thumb: "/games/phoenix-fisher.webp",
    category: "fishing",
    tag: "New",
    description:
      "Reel in fiery phoenix fish across molten tides. Boss encounters, freeze lures, and cascading coin rewards.",
    rating: 4.5,
    reviews: 900,
    rtp: "96.00%",
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱25",
    features: ["Boss Fish", "Multi-Catch", "Coin Rain", "Power Cannons"],
  },
  {
    ...defaults,
    id: "shark-hunter",
    name: "Shark Hunter",
    provider: "MaxHigh",
    thumb: "/games/shark-hunter.webp",
    category: "fishing",
    tag: "New",
    description:
      "Hunt apex sharks in deep-sea arcade combat. Boss fights, power weapons, and coin-rain payouts.",
    rating: 4.5,
    reviews: 870,
    rtp: "96.00%",
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱25",
    features: ["Boss Fish", "Multi-Catch", "Coin Rain", "Power Cannons"],
  },
  {
    ...defaults,
    id: "octopus-armada",
    name: "Octopus Armada",
    provider: "MaxHigh",
    thumb: "/games/octopus-armada.webp",
    category: "fishing",
    tag: "New",
    description:
      "Blast tentacle swarms with heavy cannons. Arcade fishing with boss octopi, net bombs, and coin rain.",
    rating: 4.4,
    reviews: 840,
    rtp: "96.00%",
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱25",
    features: ["Boss Fish", "Multi-Catch", "Coin Rain", "Power Cannons"],
  },
  {
    ...defaults,
    id: "turtle-tide",
    name: "Turtle Tide",
    provider: "MaxHigh",
    thumb: "/games/turtle-tide.webp",
    category: "fishing",
    tag: "New",
    description:
      "Ride the turtle tide and land legendary shells. Arcade fishing with boss turtles, multipliers, and coin rain.",
    rating: 4.5,
    reviews: 810,
    rtp: "96.00%",
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱25",
    features: ["Boss Fish", "Multi-Catch", "Coin Rain", "Power Cannons"],
  },
  {
    ...defaults,
    id: "whale-war",
    name: "Whale War",
    provider: "MaxHigh",
    thumb: "/games/whale-war.webp",
    category: "fishing",
    tag: "New",
    description:
      "Battle leviathan whales across stormy seas. Boss encounters, freeze lures, and cascading coin rewards.",
    rating: 4.5,
    reviews: 830,
    rtp: "96.00%",
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱25",
    features: ["Boss Fish", "Multi-Catch", "Coin Rain", "Power Cannons"],
  },
  {
    ...defaults,
    id: "frontier-gold",
    name: "Frontier Gold",
    thumb: "/games/frontier-gold.webp",
    category: "slot",
    tag: "Hot",
    description:
      "Diamond 3-4-5-4-3 · 720 ways western Hold & Win. Land 6+ Gold Coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.6,
    reviews: 2210,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways", "Hold & Win", "Jackpots", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "fruit-riot",
    name: "Fruit Riot",
    thumb: "/games/fruit-riot.webp",
    category: "slot",
    tag: "New",
    description:
      "Classic 3-reel fruit machine. Hold any reels, chase Double Wilds for 1,000×, unlock the progressive jackpot at max bet, and climb the Bonus Ladder.",
    rating: 4.4,
    reviews: 760,
    volatility: "Medium",
    maxWin: "1,000x+",
    rtp: "TBD",
    minBet: "₱1",
    maxBet: "₱5",
    features: ["3 Reels", "Hold", "Double Wild", "Progressive JP", "Bonus Ladder"],
  },
  {
    ...defaults,
    id: "crazy-sevens",
    name: "Crazy Sevens",
    thumb: "/games/crazy-sevens.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Neon classic 3-reel sevens. Hold any reels, chase Double Wilds, and climb the jackpot ladder — Fruit Riot engine in Crazy 7s skin.",
    rating: 4.5,
    reviews: 1200,
    volatility: "Medium",
    maxWin: "1,000x+",
    rtp: "TBD",
    minBet: "₱1",
    maxBet: "₱5",
    features: ["3 Reels", "Hold", "Double Wild", "Progressive JP", "Bonus Ladder"],
  },
  {
    ...defaults,
    id: "buffalo-reign",
    name: "Buffalo Reign",
    thumb: "/games/buffalo-reign.webp",
    category: "slot",
    tag: "New",
    description:
      "The buffalo rules the desert sunset. 1,024 ways, Compass wilds, Golden Campfire free spins, and Treasure Chest Hold & Collect with Explorer→Legend jackpots.",
    rating: 4.7,
    reviews: 1675,
    rtp: "96.00%",
    volatility: "High",
    maxWin: "11,000x",
    features: ["1024 Ways", "Stampede FS", "Treasure Chest", "Legend Jackpot"],
  },
  {
    ...defaults,
    id: "fire-spike",
    name: "Fire Spike",
    thumb: "/games/fire-spike.webp",
    category: "slot",
    description:
      "5×3 fire-strike reels with 10 paylines. Land 6+ Wilds and Scatters anywhere for instant mix prizes — fill the grid with Scatters for the 25,000× Grand Jackpot.",
    rating: 4.5,
    reviews: 1120,
    volatility: "High",
    maxWin: "25,000x",
    rtp: "96.5%",
    minBet: "₱0.10",
    maxBet: "₱50",
    features: ["10 Paylines", "Wild+Scatter Mix", "Grand Jackpot", "RTP Profiles"],
  },
  {
    ...defaults,
    id: "boxing-king",
    name: "Boxing King",
    thumb: "/games/boxing-king.webp",
    category: "slot",
    tag: "New",
    description:
      "5×3 boxing arena reels with 10 paylines. Land Wilds and Scatters for instant mix prizes — fill the grid with Scatters for the Grand Jackpot.",
    rating: 4.6,
    reviews: 880,
    volatility: "High",
    maxWin: "25,000x",
    rtp: "96.5%",
    minBet: "₱0.10",
    maxBet: "₱50",
    features: ["10 Paylines", "Wild+Scatter Mix", "Grand Jackpot", "RTP Profiles"],
  },
  {
    ...defaults,
    id: "goal-rush",
    name: "Goal Rush",
    thumb: "/games/goal-rush.webp",
    category: "slot",
    tag: "New",
    description:
      "5×3 soccer arena reels with 10 paylines. Land Wilds and Scatters for instant mix prizes — fill the grid with Scatters for the Grand Jackpot.",
    rating: 4.6,
    reviews: 740,
    volatility: "High",
    maxWin: "25,000x",
    rtp: "96.5%",
    minBet: "₱0.10",
    maxBet: "₱50",
    features: ["10 Paylines", "Wild+Scatter Mix", "Grand Jackpot", "RTP Profiles"],
  },
  {
    ...defaults,
    id: "money-coming",
    name: "Money Coming",
    thumb: "/games/money-coming.webp",
    category: "slot",
    tag: "Hot",
    provider: "MaxHigh",
    description:
      "Cash-rain arcade slot. 5×3 · 10 paylines with Money Coming scatters, Money Wilds, mix prizes, and a Grand Jackpot path. JILI-inspired MaxHigh original.",
    rating: 4.7,
    reviews: 3100,
    volatility: "High",
    maxWin: "25,000x",
    rtp: "96.5%",
    minBet: "₱0.10",
    maxBet: "₱50",
    features: ["10 Paylines", "Money Coming", "Mix Prizes", "Grand Jackpot"],
  },
  {
    ...defaults,
    id: "pug-den",
    name: "Pug Den",
    thumb: "/games/pug-den.webp",
    category: "slot",
    tag: "New",
    description:
      "3-4-5-4-3 diamond · 720 connecting ways. Treat Wilds stack multipliers, Treat Yo'Self sticky free spins, and Dawg's Den pooled pot with sticky Toasters. Max win 7,500×.",
    rating: 4.7,
    reviews: 640,
    volatility: "High",
    maxWin: "7,500x",
    rtp: "96.33%",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: [
      "720 Connecting Ways",
      "Diamond 3-4-5-4-3",
      "Treat Wild Multipliers",
      "Treat Yo'Self",
      "Dawg's Den",
      "Bonus Buy",
    ],
  },
  {
    ...defaults,
    id: "ace-high",
    name: "Ace High",
    thumb: "/games/ace-high.webp",
    category: "cards",
    tag: "New",
    description:
      "One card vs the dealer. Higher wins even money. Tie? Go to War. Optional Tie/War and Ace Bonus side bets. Configurable math · max 500×.",
    rating: 4.6,
    reviews: 890,
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["High Card", "Go to War", "Tie Side Bet", "Ace Bonus"],
  },
  {
    ...defaults,
    id: "baccarat",
    name: "Baccarat",
    thumb: "/games/baccarat.webp",
    category: "cards",
    tag: "New",
    description:
      "Classic Punto Banco. Bet Player, Banker, or Tie — optional Player Pair / Banker Pair. Naturals, third-card tableau, 5% Banker commission. MaxHigh original.",
    rating: 4.8,
    reviews: 2100,
    volatility: "Low",
    rtp: "98.94%",
    maxWin: "11:1",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["Punto Banco", "Player / Banker / Tie", "Pair Side Bets", "8-Deck Shoe", "Natural 8–9"],
  },
  {
    ...defaults,
    id: "lucky9",
    name: "Lucky 9",
    thumb: "/games/lucky9.webp",
    category: "cards",
    tag: "New",
    description:
      "Closer to 9 wins. Natural 9 beats any 3-card 9. Symmetric third-card rule (draw on 5 or less). Player & Dealer pay 1:1 — no commission. MaxHigh original.",
    rating: 4.7,
    reviews: 640,
    volatility: "Low",
    rtp: "98.5%",
    maxWin: "8:1",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["Closer to 9", "Natural 9", "No Commission", "Symmetric Draw", "Player / Dealer / Tie"],
  },
  {
    ...defaults,
    id: "threecardpoker",
    name: "Three Card Poker",
    thumb: "/games/threecardpoker.webp",
    category: "cards",
    tag: "New",
    description:
      "Ante / Play vs the dealer. Pair Plus side bet. Straight beats Flush. Dealer must qualify Queen-high or better. Optional Ante Bonus. MaxHigh original.",
    rating: 4.7,
    reviews: 520,
    volatility: "Medium",
    rtp: "97.6%",
    maxWin: "40:1",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["Ante / Play", "Pair Plus", "Dealer Qualify", "Ante Bonus", "Play or Fold"],
  },
  {
    ...defaults,
    id: "color-game",
    name: "Color Game",
    thumb: "/games/color-game.webp",
    category: "cards",
    tag: "New",
    description:
      "PH perya Color Game. Chip up on red, yellow, blue, green, white, or pink. One winning color pays ~5.5×. MaxHigh original.",
    rating: 4.6,
    reviews: 410,
    volatility: "Low",
    rtp: "91.7%",
    maxWin: "5.5x",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["6 Colors", "Multi-spot Bets", "Wheel Reveal", "Configurable Pays"],
  },
  {
    ...defaults,
    id: "tongits-arena",
    name: "Tongits Arena",
    thumb: "/games/tongits-arena.webp",
    category: "cards",
    tag: "New",
    description:
      "Fight pot Ante/Play arena. Pair Plus side pot. v1 uses Three Card Poker session math — full Tongits meld rules TBD. MaxHigh original.",
    rating: 4.6,
    reviews: 280,
    volatility: "Medium",
    rtp: "97.6%",
    maxWin: "40:1",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["Fight Pot", "Play or Fold", "Side Pot", "Dealer Qualify"],
  },
  {
    ...defaults,
    id: "lucky-drop",
    name: "Lucky Drop",
    thumb: "/games/lucky-drop.webp",
    category: "cards",
    tag: "New",
    description:
      "Pick up to 3 lanes from 1–10. One number drops — hit pays 9×. Instant settle. MaxHigh original.",
    rating: 4.5,
    reviews: 190,
    volatility: "Medium",
    rtp: "90%",
    maxWin: "9x",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["1–10 Drop", "Multi-lane", "Instant Settle", "9× Pays"],
  },
  {
    ...defaults,
    id: "color-game-pro",
    name: "Color Game Pro",
    thumb: "/games/color-game-pro.webp",
    category: "cards",
    tag: "New",
    description:
      "Pro perya Color Game. Chip up on six colors — one winner pays ~5.5×. MaxHigh original.",
    rating: 4.6,
    reviews: 360,
    volatility: "Low",
    rtp: "91.7%",
    maxWin: "5.5x",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["6 Colors", "Multi-spot Bets", "Wheel Reveal", "Configurable Pays"],
  },
  {
    ...defaults,
    id: "lucky-nine-plus",
    name: "Lucky Nine Plus",
    thumb: "/games/lucky-nine-plus.webp",
    category: "cards",
    tag: "New",
    description:
      "Closer to 9 wins — Natural 9 beats any 3-card 9. Symmetric draw, no commission. MaxHigh original.",
    rating: 4.7,
    reviews: 520,
    volatility: "Low",
    rtp: "98.5%",
    maxWin: "8:1",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["Closer to 9", "Natural 9", "No Commission", "Symmetric Draw", "Player / Dealer / Tie"],
  },
  {
    ...defaults,
    id: "drop-deluxe",
    name: "Drop Deluxe",
    thumb: "/games/drop-deluxe.webp",
    category: "cards",
    tag: "New",
    description:
      "Deluxe number drop — pick up to 3 lanes from 1–10. Hit pays 9×. Instant settle. MaxHigh original.",
    rating: 4.5,
    reviews: 170,
    volatility: "Medium",
    rtp: "90%",
    maxWin: "9x",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["1–10 Drop", "Multi-lane", "Instant Settle", "9× Pays"],
  },
  {
    ...defaults,
    id: "poker-showdown",
    name: "Poker Showdown",
    thumb: "/games/poker-showdown.webp",
    category: "cards",
    tag: "New",
    description:
      "Ante/Play showdown with Pair Plus side pot. Dealer must qualify Queen-high. MaxHigh original.",
    rating: 4.6,
    reviews: 250,
    volatility: "Medium",
    rtp: "97.6%",
    maxWin: "40:1",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["Fight Pot", "Play or Fold", "Side Pot", "Dealer Qualify"],
  },
  {
    ...defaults,
    id: "super-ace",
    name: "Super Ace",
    thumb: "/games/super-ace.webp",
    category: "slot",
    tag: "Hot",
    provider: "JILI",
    description: "Experience high-octane card action with Super Ace! Golden cards, combo cascades, and massive card multipliers.",
    rating: 4.9,
    reviews: 5410,
    volatility: "Medium",
    maxWin: "1,500x",
    features: ["Golden Cards", "Little & Big Joker", "Combo Multipliers", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "mega-ace",
    name: "Mega Ace",
    thumb: "/games/mega-ace.webp",
    category: "slot",
    tag: "New",
    provider: "JILI",
    description:
      "Mega Ace deals golden cards, joker transforms, cascading combos, and free-spin multipliers across a 5×4 ways grid.",
    rating: 4.9,
    reviews: 2100,
    volatility: "Medium",
    maxWin: "1,500x",
    rtp: "97.0%",
    features: ["Golden Cards", "Little & Big Joker", "Combo Multipliers", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "fortune-gems",
    name: "Fortune Gems",
    thumb: "/games/fortune-gems.webp",
    category: "slot",
    tag: "Hot",
    provider: "MaxHigh",
    description:
      "3×3 temple gems with 5 fixed paylines and a dedicated multiplier reel (1×–15×). Extra Bet (EX) raises stake 50% for better multiplier odds. No free spins or bonus rounds.",
    rating: 4.8,
    reviews: 4200,
    // TODO/config-pending — conflicting sources cite 97% / 96.65% / 95.22% floor
    rtp: "97%*",
    volatility: "Medium",
    // TODO/config-pending — 375× single-sourced / unconfirmed
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Wild"],
  },
  {
    ...defaults,
    id: "fortune-ox",
    name: "Fortune Ox",
    thumb: "/games/fortune-ox.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Year of the Ox prosperity slot. Same 3×3 + multiplier reel math as Fortune Gems — Extra Bet (EX) for richer mult odds. No free spins.",
    rating: 4.8,
    reviews: 1800,
    rtp: "97%*",
    volatility: "Medium",
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Ox Wild"],
  },
  {
    ...defaults,
    id: "fortune-tiger",
    name: "Fortune Tiger",
    thumb: "/games/fortune-tiger.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Year of the Tiger prosperity slot. Same 3×3 + multiplier reel math as Fortune Gems — Extra Bet (EX) for richer mult odds. No free spins.",
    rating: 4.8,
    reviews: 2100,
    rtp: "97%*",
    volatility: "Medium",
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Tiger Wild"],
  },
  {
    ...defaults,
    id: "fortune-rabbit",
    name: "Fortune Rabbit",
    thumb: "/games/fortune-rabbit.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Year of the Rabbit prosperity slot. Same 3×3 + multiplier reel math as Fortune Gems — Extra Bet (EX) for richer mult odds. No free spins.",
    rating: 4.8,
    reviews: 1950,
    rtp: "97%*",
    volatility: "Medium",
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Rabbit Wild"],
  },
  {
    ...defaults,
    id: "dust-dollars",
    name: "Dust & Dollars",
    thumb: "/games/dust-dollars.webp",
    category: "slot",
    tag: "Hot",
    description:
      "Diamond 3-4-5-4-3 · 720 ways western Hold & Win. Land 6+ Gold Coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.6,
    reviews: 1840,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways", "Hold & Win", "Jackpots", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "cleopatra-gold",
    name: "Cleopatra Gold",
    thumb: "/games/cleopatra-gold.webp",
    category: "slot",
    tag: "New",
    description:
      "Egyptian 1,024 ways with cascade multipliers, Golden Campfire free spins, and Treasure Chest Hold & Collect with Explorer→Legend jackpots.",
    rating: 4.7,
    reviews: 1520,
    rtp: "96.00%",
    volatility: "High",
    maxWin: "11,000x",
    features: ["1024 Ways", "Golden Campfire FS", "Treasure Chest", "Legend Jackpot"],
  },

  {
    ...defaults,
    id: "pinata-wins",
    name: "Piñata Wins",
    thumb: "/games/pinata-wins.webp",
    category: "slot",
    tag: "New",
    provider: "PG Soft",
    description: "Burst open the festive star piñata for exploding wild frames, coin showers, and high-energy party spins.",
    rating: 4.7,
    reviews: 1950,
    rtp: "96.75%",
    volatility: "Medium",
    maxWin: "5,000x",
    features: ["Gold Framed Symbols", "Exploding Wilds", "Fiesta Free Spins"],
  },
  {
    ...defaults,
    id: "gold-mine",
    name: "Gold Mine Dig",
    thumb: "/games/gold-mine.webp",
    category: "slot",
    tag: "New",
    description:
      "Diamond 3-4-5-4-3 · 720 ways Hold & Win dig. Land 6+ Gold Coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.6,
    reviews: 1620,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways", "Hold & Win", "Jackpots", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "jeepney-jackpot",
    name: "Jeepney Jackpot",
    thumb: "/games/jeepney-jackpot.webp",
    category: "slot",
    tag: "New",
    description:
      "Diamond 3-4-5-4-3 · 720 ways Manila Hold & Win. Land 6+ coins for jeepney respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.6,
    reviews: 1480,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways", "Hold & Win", "Jackpots", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "sari-sari-spin",
    name: "Sari-Sari Spin",
    thumb: "/games/sari-sari-spin.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Neighborhood sari-sari store luck. Same 3×3 + multiplier reel math as Fortune Ox — Extra Bet (EX) for richer mult odds. No free spins.",
    rating: 4.8,
    reviews: 1320,
    rtp: "97%*",
    volatility: "Medium",
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Wild"],
  },

  {
    ...defaults,
    id: "lucky-neko",
    name: "Lucky Neko",
    thumb: "/games/lucky-neko.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Lucky cat prosperity slot. Same 3×3 + multiplier reel math as Fortune Ox — Extra Bet (EX) for richer mult odds. No free spins.",
    rating: 4.8,
    reviews: 1650,
    rtp: "97%*",
    volatility: "Medium",
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Neko Wild"],
  },
  {
    ...defaults,
    id: "fortune-mouse",
    name: "Fortune Mouse",
    thumb: "/games/fortune-mouse.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Year of the Mouse prosperity slot. Same 3×3 + multiplier reel math as Fortune Ox — Extra Bet (EX) for richer mult odds. No free spins.",
    rating: 4.8,
    reviews: 1580,
    rtp: "97%*",
    volatility: "Medium",
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Mouse Wild"],
  },
  {
    ...defaults,
    id: "prosperity-lion",
    name: "Prosperity Lion",
    thumb: "/games/prosperity-lion.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Guardian lion prosperity slot. Same 3×3 + multiplier reel math as Fortune Tiger — Extra Bet (EX) for richer mult odds. No free spins.",
    rating: 4.8,
    reviews: 1720,
    rtp: "97%*",
    volatility: "Medium",
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Lion Wild"],
  },
  {
    ...defaults,
    id: "coin-volcano",
    name: "Coin Volcano",
    thumb: "/games/coin-volcano.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Volcanic cash-rain arcade slot. 5×3 · 10 paylines with scatters, wilds, mix prizes, and a Grand Jackpot path — Money Coming math in lava skin.",
    rating: 4.7,
    reviews: 1400,
    volatility: "High",
    maxWin: "25,000x",
    rtp: "96.5%",
    minBet: "₱0.10",
    maxBet: "₱50",
    features: ["10 Paylines", "Coin Volcano", "Mix Prizes", "Grand Jackpot"],
  },
  {
    ...defaults,
    id: "cash-mania",
    name: "Cash Mania",
    thumb: "/games/cash-mania.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "High-energy cash arcade slot. 5×3 · 10 paylines with scatters, wilds, mix prizes, and a Grand Jackpot path — Money Coming math in mania skin.",
    rating: 4.7,
    reviews: 1350,
    volatility: "High",
    maxWin: "25,000x",
    rtp: "96.5%",
    minBet: "₱0.10",
    maxBet: "₱50",
    features: ["10 Paylines", "Cash Mania", "Mix Prizes", "Grand Jackpot"],
  },
  {
    ...defaults,
    id: "zeus-strike",
    name: "Zeus Strike",
    thumb: "/games/zeus-strike.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Zeus strikes with cascading ways, progressive multipliers, free spins, and buy-feature thunder — Olympus Wrath math in strike skin.",
    rating: 4.8,
    reviews: 1900,
    rtp: "96.4%",
    volatility: "Very High",
    maxWin: "15,000x",
    features: ["Cascading Wins", "Ways", "Free Spins", "Buy Bonus", "Progressive Mult"],
  },
  {
    ...defaults,
    id: "thor-thunder",
    name: "Thor Thunder",
    thumb: "/games/thor-thunder.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Thor's hammer cascades with ways wins, progressive multipliers, free spins, and buy-feature thunder — Olympus Wrath math in Norse skin.",
    rating: 4.8,
    reviews: 1850,
    rtp: "96.4%",
    volatility: "Very High",
    maxWin: "15,000x",
    features: ["Cascading Wins", "Ways", "Free Spins", "Buy Bonus", "Progressive Mult"],
  },
  {
    ...defaults,
    id: "maya-gold",
    name: "Maya Gold",
    thumb: "/games/maya-gold.webp",
    category: "slot",
    tag: "New",
    description:
      "Raid a Maya temple for cascading cluster wins, bomb multipliers, ante bets, and free-spin treasure hunts.",
    rating: 4.9,
    reviews: 980,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "10,000x",
    minBet: "₱0.20",
    maxBet: "₱200",
    features: ["Cascading Wins", "Free Spins", "Buy Bonus", "Multipliers", "Ante Bet"],
  },
  {
    ...defaults,
    id: "temple-rush",
    name: "Temple Rush",
    thumb: "/games/temple-rush.webp",
    category: "slot",
    tag: "New",
    description:
      "Race through ancient temples for cascading cluster wins, bomb multipliers, ante bets, and free-spin treasure hunts.",
    rating: 4.9,
    reviews: 910,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "10,000x",
    minBet: "₱0.20",
    maxBet: "₱200",
    features: ["Cascading Wins", "Free Spins", "Buy Bonus", "Multipliers", "Ante Bet"],
  },
  {
    ...defaults,
    id: "mahjong-ways-3",
    name: "Mahjong Ways 3",
    thumb: "/games/mahjong-ways-3.webp",
    category: "slot",
    tag: "New",
    description:
      "The third chapter returns with 5×4 ways, cascading tumble drops, gold wild transforms, and progressive cascade multipliers — plus free spins and buy bonus.",
    rating: 5.0,
    reviews: 720,
    rtp: "96.9%",
    volatility: "High",
    maxWin: "2,893x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["Dynamic Ways", "Cascading Tumble", "Gold Wild Transform", "Progressive Multiplier", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "wild-ace",
    name: "Wild Ace",
    thumb: "/games/wild-ace.webp",
    category: "slot",
    tag: "New",
    provider: "JILI",
    description:
      "Wild Ace deals golden cards, joker transforms, cascading combos, and free-spin multipliers across a 5×4 ways grid.",
    rating: 4.9,
    reviews: 1800,
    volatility: "Medium",
    maxWin: "1,500x",
    rtp: "97.0%",
    features: ["Golden Cards", "Little & Big Joker", "Combo Multipliers", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "royal-ace",
    name: "Royal Ace",
    thumb: "/games/royal-ace.webp",
    category: "slot",
    tag: "New",
    provider: "JILI",
    description:
      "Experience high-octane card action with Royal Ace! Golden cards, combo cascades, and massive card multipliers.",
    rating: 4.9,
    reviews: 2100,
    volatility: "Medium",
    maxWin: "1,500x",
    features: ["Golden Cards", "Little & Big Joker", "Combo Multipliers", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "neon-fruits",
    name: "Neon Fruits",
    thumb: "/games/neon-fruits.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Neon classic 3-reel fruits. Hold any reels, chase Double Wilds, and climb the jackpot ladder — Crazy Sevens engine in neon fruit skin.",
    rating: 4.5,
    reviews: 1100,
    volatility: "Medium",
    maxWin: "1,000x+",
    rtp: "TBD",
    minBet: "₱1",
    maxBet: "₱5",
    features: ["3 Reels", "Hold", "Double Wild", "Progressive JP", "Bonus Ladder"],
  },
  {
    ...defaults,
    id: "lucky-bars",
    name: "Lucky Bars",
    thumb: "/games/lucky-bars.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Classic 3-reel bars cabinet. Hold any reels, chase Double Wilds, and climb the jackpot ladder — Crazy Sevens engine in lucky bars skin.",
    rating: 4.5,
    reviews: 1050,
    volatility: "Medium",
    maxWin: "1,000x+",
    rtp: "TBD",
    minBet: "₱1",
    maxBet: "₱5",
    features: ["3 Reels", "Hold", "Double Wild", "Progressive JP", "Bonus Ladder"],
  },
  {
    ...defaults,
    id: "carabao-charge",
    name: "Carabao Charge",
    thumb: "/games/carabao-charge.webp",
    category: "slot",
    tag: "New",
    description:
      "Filipino 1,024 ways with cascade multipliers, Golden Campfire free spins, and Treasure Chest Hold & Collect with Explorer→Legend jackpots.",
    rating: 4.7,
    reviews: 1290,
    rtp: "96.00%",
    volatility: "High",
    maxWin: "11,000x",
    features: ["1024 Ways", "Golden Campfire FS", "Treasure Chest", "Legend Jackpot"],
  },
  // Wave B clones
  {
    ...defaults,
    id: "knockout-king",
    name: "Knockout King",
    thumb: "/games/knockout-king.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "5×3 boxing arena reels with 10 paylines. Land Wilds and Scatters for instant mix prizes — fill the grid with Scatters for the Grand Jackpot.",
    rating: 4.7,
    reviews: 820,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "25,000x",
    minBet: "₱0.10",
    maxBet: "₱50",
    features: ["10 Paylines","Wild+Scatter Mix","Grand Jackpot","RTP Profiles"],
  },
  {
    ...defaults,
    id: "arena-champ",
    name: "Arena Champ",
    thumb: "/games/arena-champ.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "5×3 sports arena reels with 10 paylines. Land Wilds and Scatters for instant mix prizes — fill the grid with Scatters for the Grand Jackpot.",
    rating: 4.7,
    reviews: 710,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "25,000x",
    minBet: "₱0.10",
    maxBet: "₱50",
    features: ["10 Paylines","Wild+Scatter Mix","Grand Jackpot","RTP Profiles"],
  },
  {
    ...defaults,
    id: "safari-gold",
    name: "Safari Gold",
    thumb: "/games/safari-gold.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Safari 1,024 ways with cascade multipliers, Golden Campfire free spins, and Treasure Chest Hold & Collect with Explorer→Legend jackpots.",
    rating: 4.7,
    reviews: 1180,
    rtp: "96.00%",
    volatility: "High",
    maxWin: "11,000x",
    features: ["1024 Ways","Golden Campfire FS","Treasure Chest","Legend Jackpot"],
  },
  {
    ...defaults,
    id: "pharaoh-fire",
    name: "Pharaoh Fire",
    thumb: "/games/pharaoh-fire.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Egyptian 1,024 ways with cascade multipliers, Golden Campfire free spins, and Treasure Chest Hold & Collect with Explorer→Legend jackpots.",
    rating: 4.7,
    reviews: 1410,
    rtp: "96.00%",
    volatility: "High",
    maxWin: "11,000x",
    features: ["1024 Ways","Golden Campfire FS","Treasure Chest","Legend Jackpot"],
  },
  {
    ...defaults,
    id: "desert-riches",
    name: "Desert Riches",
    thumb: "/games/desert-riches.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Diamond 3-4-5-4-3 · 720 ways desert Hold & Win. Land 6+ Gold Coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.7,
    reviews: 1520,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways","Hold & Win","Jackpots","Free Spins","Buy Bonus"],
  },
  {
    ...defaults,
    id: "outlaw-coins",
    name: "Outlaw Coins",
    thumb: "/games/outlaw-coins.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Diamond 3-4-5-4-3 · 720 ways outlaw Hold & Win. Land 6+ Gold Coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.7,
    reviews: 1390,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways","Hold & Win","Jackpots","Free Spins","Buy Bonus"],
  },
  {
    ...defaults,
    id: "crystal-cave",
    name: "Crystal Cave",
    thumb: "/games/crystal-cave.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Diamond 3-4-5-4-3 · 720 ways crystal Hold & Win dig. Land 6+ coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.7,
    reviews: 1280,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways","Hold & Win","Jackpots","Free Spins","Buy Bonus"],
  },
  {
    ...defaults,
    id: "diamond-dig",
    name: "Diamond Dig",
    thumb: "/games/diamond-dig.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Diamond 3-4-5-4-3 · 720 ways Hold & Win dig. Land 6+ Gold Coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.7,
    reviews: 1340,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways","Hold & Win","Jackpots","Free Spins","Buy Bonus"],
  },
  {
    ...defaults,
    id: "candy-blast",
    name: "Candy Blast",
    thumb: "/games/candy-blast.webp",
    category: "slot",
    tag: "Hot",
    provider: "MaxHigh",
    description:
      "Blast the sugar mountain — cascading wins, sticky sweets, and a progressive Peak Bonus. Match candy clusters, unlock free spins, and chase the Super Peak jackpot.",
    rating: 4.7,
    reviews: 3200,
    rtp: "96.8%",
    volatility: "High",
    maxWin: "12,500x",
    minBet: "₱0.10",
    maxBet: "₱250",
    features: ["Cascading Wins","Peak Bonus","Sticky Wilds","Free Spins","Buy Bonus"],
  },
  {
    ...defaults,
    id: "sweet-rush",
    name: "Sweet Rush",
    thumb: "/games/sweet-rush.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Island candy cascades. Cluster tumbles, bounce multipliers, free spins, and buy-feature beach chaos.",
    rating: 4.7,
    reviews: 1980,
    volatility: "Medium",
    maxWin: "8,000x",
    features: ["Tumble Wins","Cluster Pays","Free Spins","Wild Multipliers"],
  },
  {
    ...defaults,
    id: "starlight-ways",
    name: "Starlight Ways",
    thumb: "/games/starlight-ways.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "5×5 ways cascade with Golden→Wild transforms, climbing multipliers, and Free Spins with a Guaranteed Golden Reel.",
    rating: 4.7,
    reviews: 1420,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "100,000x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["3,125 Ways","Golden→Wild","Cascade Mult","FS Golden Reel","Buy Bonus"],
  },
  {
    ...defaults,
    id: "galaxy-ace",
    name: "Galaxy Ace",
    thumb: "/games/galaxy-ace.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "5×5 ways cascade with Golden→Wild transforms, climbing multipliers, and Free Spins with a Guaranteed Golden Reel.",
    rating: 4.7,
    reviews: 1680,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "100,000x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["3,125 Ways","Golden→Wild","Cascade Mult","FS Golden Reel","Buy Bonus"],
  },
  {
    ...defaults,
    id: "gate-of-ra",
    name: "Gate of Ra",
    thumb: "/games/gate-of-ra.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Mystical Ra cascades with ways wins, progressive multipliers, free spins, and buy-feature magic — Enchanted Grove math in Egyptian skin.",
    rating: 4.7,
    reviews: 1890,
    rtp: "96.4%",
    volatility: "Very High",
    maxWin: "15,000x",
    features: ["Cascading Wins","Ways","Free Spins","Buy Bonus","Progressive Mult"],
  },
  {
    ...defaults,
    id: "mystic-runes",
    name: "Mystic Runes",
    thumb: "/games/mystic-runes.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Mystic rune cascades with ways wins, progressive multipliers, free spins, and buy-feature magic — Enchanted Grove math in rune skin.",
    rating: 4.7,
    reviews: 1750,
    rtp: "96.4%",
    volatility: "Very High",
    maxWin: "15,000x",
    features: ["Cascading Wins","Ways","Free Spins","Buy Bonus","Progressive Mult"],
  },

  // Wave C clones
  {
    ...defaults,
    id: "halo-halo-hits",
    name: "Halo-Halo Hits",
    thumb: "/games/halo-halo-hits.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Neighborhood halo-halo luck. Same 3×3 + multiplier reel math as Fortune Ox — Extra Bet (EX) for richer mult odds. No free spins.",
    rating: 4.8,
    reviews: 1280,
    rtp: "97%*",
    volatility: "Medium",
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Wild"],
  },

  {
    ...defaults,
    id: "balut-bonus",
    name: "Balut Bonus",
    thumb: "/games/balut-bonus.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Street-food balut luck. Same 3×3 + multiplier reel math as Fortune Ox — Extra Bet (EX) for richer mult odds. No free spins.",
    rating: 4.8,
    reviews: 1180,
    rtp: "97%*",
    volatility: "Medium",
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Wild"],
  },

  {
    ...defaults,
    id: "sinigang-spin",
    name: "Sinigang Spin",
    thumb: "/games/sinigang-spin.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Sour soup fiesta! 5×3 fixed paylines with Dragon Fireworks, Monkey Free Spins, Extra Scatter wheel, and optional Gamble.",
    rating: 5,
    reviews: 720,
    rtp: "96.02%",
    volatility: "High",
    maxWin: "12,000x",
    minBet: "₱0.50",
    maxBet: "₱600",
    features: ["20 Paylines", "Dragon Fireworks", "Monkey Free Spins", "Extra Scatter", "Gamble"],
  },

  {
    ...defaults,
    id: "lechon-luck",
    name: "Lechon Luck",
    thumb: "/games/lechon-luck.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Roast lechon fiesta! 5×3 fixed paylines with Dragon Fireworks, Monkey Free Spins, Extra Scatter wheel, and optional Gamble.",
    rating: 5,
    reviews: 680,
    rtp: "96.02%",
    volatility: "High",
    maxWin: "12,000x",
    minBet: "₱0.50",
    maxBet: "₱600",
    features: ["20 Paylines", "Dragon Fireworks", "Monkey Free Spins", "Extra Scatter", "Gamble"],
  },

  {
    ...defaults,
    id: "lantern-luck",
    name: "Lantern Luck",
    thumb: "/games/lantern-luck.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Lantern night fireworks! 5×3 fixed paylines with Dragon Fireworks, Monkey Free Spins, Extra Scatter wheel, and optional Gamble.",
    rating: 5,
    reviews: 700,
    rtp: "96.02%",
    volatility: "High",
    maxWin: "12,000x",
    minBet: "₱0.50",
    maxBet: "₱600",
    features: ["20 Paylines", "Dragon Fireworks", "Monkey Free Spins", "Extra Scatter", "Gamble"],
  },

  {
    ...defaults,
    id: "palengke-pays",
    name: "Palengke Pays",
    thumb: "/games/palengke-pays.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Market-day Hold & Win. Diamond 3-4-5-4-3 · 720 ways. Land 6+ coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.6,
    reviews: 1360,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways", "Hold & Win", "Jackpots", "Free Spins", "Buy Bonus"],
  },

  {
    ...defaults,
    id: "tricycle-treasure",
    name: "Tricycle Treasure",
    thumb: "/games/tricycle-treasure.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Trike-route Hold & Win. Diamond 3-4-5-4-3 · 720 ways. Land 6+ coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.6,
    reviews: 1290,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["720 Ways", "Hold & Win", "Jackpots", "Free Spins", "Buy Bonus"],
  },

  {
    ...defaults,
    id: "beach-bonanza",
    name: "Beach Bonanza",
    thumb: "/games/beach-bonanza.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Beach candy cascades. Cluster tumbles, bounce multipliers, free spins, and buy-feature beach chaos.",
    rating: 4.7,
    reviews: 1980,
    rtp: "96.5%",
    volatility: "Medium",
    maxWin: "8,000x",
    minBet: "₱0.20",
    maxBet: "₱100",
    features: ["Tumble Wins", "Cluster Pays", "Free Spins", "Wild Multipliers"],
  },

  {
    ...defaults,
    id: "island-fever",
    name: "Island Fever",
    thumb: "/games/island-fever.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Island cascading cluster wins — sticky sweets, progressive Peak Bonus, free spins, and buy feature.",
    rating: 4.9,
    reviews: 1880,
    rtp: "96.8%",
    volatility: "High",
    maxWin: "12,500x",
    minBet: "₱0.10",
    maxBet: "₱250",
    features: ["Cascading Wins", "Peak Bonus", "Sticky Wilds", "Free Spins", "Buy Bonus"],
  },

  {
    ...defaults,
    id: "neon-makati",
    name: "Neon Makati",
    thumb: "/games/neon-makati.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Neon Makati skyline cascade: 5×5 ways with Golden→Wild transforms, climbing multipliers, and Free Spins with a Guaranteed Golden Reel.",
    rating: 4.7,
    reviews: 1490,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "100,000x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["3,125 Ways", "Golden→Wild", "Cascade Mult", "FS Golden Reel", "Buy Bonus"],
  },

  {
    ...defaults,
    id: "quezon-quest",
    name: "Quezon Quest",
    thumb: "/games/quezon-quest.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Quezon City neon cascade: 5×5 ways with Golden→Wild transforms, climbing multipliers, and Free Spins with a Guaranteed Golden Reel.",
    rating: 4.7,
    reviews: 1410,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "100,000x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["3,125 Ways", "Golden→Wild", "Cascade Mult", "FS Golden Reel", "Buy Bonus"],
  },

  {
    ...defaults,
    id: "carabao-cash",
    name: "Carabao Cash",
    thumb: "/games/carabao-cash.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Filipino 1,024 ways with cascade multipliers, Golden Campfire free spins, and Treasure Chest Hold & Collect with Explorer→Legend jackpots.",
    rating: 4.7,
    reviews: 1220,
    rtp: "96.00%",
    volatility: "High",
    maxWin: "11,000x",
    minBet: "₱0.20",
    maxBet: "₱100",
    features: ["1024 Ways", "Golden Campfire FS", "Treasure Chest", "Legend Jackpot"],
  },

  {
    ...defaults,
    id: "rice-field-riches",
    name: "Rice Field Riches",
    thumb: "/games/rice-field-riches.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Rice-paddy 1,024 ways with cascade multipliers, Golden Campfire free spins, and Treasure Chest Hold & Collect with Explorer→Legend jackpots.",
    rating: 4.7,
    reviews: 1150,
    rtp: "96.00%",
    volatility: "High",
    maxWin: "11,000x",
    minBet: "₱0.20",
    maxBet: "₱100",
    features: ["1024 Ways", "Golden Campfire FS", "Treasure Chest", "Legend Jackpot"],
  },

  {
    ...defaults,
    id: "wild-panther",
    name: "Wild Panther",
    thumb: "/games/wild-panther.webp",
    category: "slot",
    tag: "New",
    provider: "MaxHigh",
    description:
      "Raid the jungle for cascading cluster wins, bomb multipliers, ante bets, and free-spin treasure hunts.",
    rating: 4.9,
    reviews: 980,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "10,000x",
    minBet: "₱0.20",
    maxBet: "₱200",
    features: ["Cascading Wins", "Free Spins", "Buy Bonus", "Multipliers", "Ante Bet"],
  },

];

export function gamesByCategory(category: GameCategory) {
  return slotGames.filter((g) => g.category === category);
}

export function getGameById(id: string) {
  return slotGames.find((g) => g.id === id);
}
