export type GameCategory = "slot" | "cards" | "fishing";

export type SlotGame = {
  id: string;
  name: string;
  provider: string;
  thumb: string;
  category: GameCategory;
  tag?: string;
  description: string;
  rating: number;
  reviews: number;
  rtp: string;
  volatility: "Low" | "Medium" | "High" | "Very High";
  maxWin: string;
  minBet: string;
  maxBet: string;
  features: string[];
};

const defaults = {
  provider: "MaxHigh",
  rating: 4.6,
  reviews: 1280,
  rtp: "96.5%",
  volatility: "Medium" as const,
  maxWin: "5,000x",
  minBet: "₱0.20",
  maxBet: "₱100",
  features: ["Free Spins", "Multipliers", "Wilds"],
};

/** MaxHigh original titles with thumbnail art */
export const slotGames: SlotGame[] = [
  {
    ...defaults,
    id: "mahjong-ways",
    name: "Mahjong Ways",
    thumb: "/games/mahjong-ways.png",
    category: "slot",
    tag: "Hot",
    description: "Experience the thrilling Chinese tile slot with dynamic Left-to-Right ways, cascading tumble drops, transforming Gold Wilds, and progressive win multipliers!",
    rating: 5.0,
    reviews: 1420,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "25,000x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["Dynamic Ways", "Cascading Tumble", "Gold Wild Transform", "Progressive Multiplier", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "chinese-new-year",
    name: "Chinese New Year",
    thumb: "/games/chinese-new-year.png",
    category: "slot",
    tag: "Hot",
    description:
      "Gong Xi Fa Cai! 5×3 fixed paylines with Dragon Fireworks, Monkey Free Spins, Extra Scatter wheel, and optional Gamble.",
    rating: 5.0,
    reviews: 820,
    rtp: "96.02%",
    volatility: "Med-High",
    maxWin: "12,000x",
    minBet: "₱0.50",
    maxBet: "₱600",
    features: [
      "20 Paylines",
      "Dragon Fireworks",
      "Monkey Free Spins",
      "Extra Scatter",
      "Gamble",
    ],
  },
  {
    ...defaults,
    id: "golden-panther",
    name: "Golden Panther",
    thumb: "/images/thumbnails/panther_thumb.png",
    category: "slot",
    tag: "New",
    description: "Explore the golden jungle temple and uncover the majestic Golden Panther's hidden treasures with cascading wins and multipliers.",
    rating: 4.9,
    reviews: 512,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "10,000x",
    minBet: "₱0.20",
    maxBet: "₱200",
    features: ["Cascading Wins", "Free Spins", "Buy Bonus", "Multipliers"],
  },
  {
    ...defaults,
    id: "candy-peak",
    name: "Candy Peak",
    thumb: "/games/candy-peak.png",
    category: "slot",
    tag: "Hot",
    description:
      "Climb the sugar mountain in Candy Peak — a colorful MaxHigh original packed with cascading wins, sticky sweets, and a progressive Peak Bonus. Match candy clusters, unlock free spins, and chase the Super Peak jackpot.",
    rating: 4.9,
    reviews: 4821,
    rtp: "96.8%",
    volatility: "High",
    maxWin: "12,500x",
    minBet: "₱0.10",
    maxBet: "₱250",
    features: ["Cascading Wins", "Peak Bonus", "Sticky Wilds", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "godly-gates",
    name: "Godly Gates",
    thumb: "/games/godly-gates.png",
    category: "slot",
    tag: "New",
    description:
      "Enter the temple of thunder. Godly Gates rains multipliers from the sky — hit the sacred gates for divine free spins and lightning payouts.",
    rating: 4.8,
    reviews: 2104,
    rtp: "96.4%",
    volatility: "Very High",
    maxWin: "15,000x",
    features: ["Cascading Wins", "Ways", "Free Spins", "Buy Bonus", "Progressive Mult"],
  },
  {
    ...defaults,
    id: "sugar-surge",
    name: "Sugar Surge",
    thumb: "/games/sugar-surge.png",
    category: "slot",
    tag: "Hot",
    description:
      "A sugar rush of tumbling wins. Fill the gumball meter to trigger Surge Mode and explode the reels with candy chaos.",
    rating: 4.7,
    reviews: 3560,
    volatility: "Medium",
    maxWin: "8,000x",
    features: ["Tumble Wins", "Surge Meter", "Free Spins", "Wild Multipliers"],
  },
  {
    ...defaults,
    id: "starlight-ace",
    name: "Starlight Ace",
    thumb: "/games/starlight-ace.png",
    category: "slot",
    tag: "New",
    description:
      "5×5 ways cascade with Golden→Wild transforms, climbing multipliers, and Free Spins with a Guaranteed Golden Reel.",
    rating: 4.7,
    reviews: 1890,
    rtp: "96.5%",
    volatility: "High",
    maxWin: "100,000x",
    minBet: "₱0.20",
    maxBet: "₱250",
    features: ["3,125 Ways", "Golden→Wild", "Cascade Mult", "FS Golden Reel", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "deep-bass",
    name: "Deep Bass",
    thumb: "/games/deep-bass.png",
    category: "fishing",
    description:
      "Dive deep and land the legendary bass. Arcade fishing action with boss fish, multipliers, and coin rain rewards.",
    rating: 4.5,
    reviews: 980,
    volatility: "Medium",
    maxWin: "2,000x",
    features: ["Boss Fish", "Multi-Catch", "Coin Rain", "Power Cannons"],
  },
  {
    ...defaults,
    id: "frontier-gold",
    name: "Frontier Gold",
    thumb: "/games/frontier-gold.png",
    category: "slot",
    tag: "Hot",
    description:
      "5×3 · 25 lines western Hold & Win. Land 6+ Gold Coins for respins, Scatters for Free Spins, and chase Mini–Grand jackpots.",
    rating: 4.6,
    reviews: 2210,
    rtp: "96.26%",
    volatility: "Medium",
    maxWin: "10,257x",
    minBet: "₱0.25",
    maxBet: "₱35",
    features: ["25 Paylines", "Hold & Win", "Jackpots", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "fruit-riot",
    name: "Fruit Riot",
    thumb: "/games/fruit-riot.png",
    category: "slot",
    tag: "New",
    description:
      "Classic 3-reel fruit machine. Hold any reels, chase Double Wilds for 1,000×, unlock the progressive jackpot at max bet, and climb the Bonus Ladder.",
    rating: 4.4,
    reviews: 760,
    volatility: "Medium",
    maxWin: "1,000x+",
    rtp: "TBD",
    minBet: "₱1",
    maxBet: "₱5",
    features: ["3 Reels", "Hold", "Double Wild", "Progressive JP", "Bonus Ladder"],
  },
  {
    ...defaults,
    id: "buffalo-reign",
    name: "Buffalo Reign",
    thumb: "/games/buffalo-reign.png",
    category: "slot",
    tag: "New",
    description:
      "The buffalo rules the desert sunset. 1,024 ways, Compass wilds, Golden Campfire free spins, and Treasure Chest Hold & Collect with Explorer→Legend jackpots.",
    rating: 4.7,
    reviews: 1675,
    rtp: "96.00%",
    volatility: "High",
    maxWin: "11,000x",
    features: ["1024 Ways", "Stampede FS", "Treasure Chest", "Legend Jackpot"],
  },
  {
    ...defaults,
    id: "fire-spike",
    name: "Fire Spike",
    thumb: "/games/fire-spike.png",
    category: "slot",
    description:
      "5×3 fire-strike reels with 10 paylines. Land 6+ Wilds and Scatters anywhere for instant mix prizes — fill the grid with Scatters for the 25,000× Grand Jackpot.",
    rating: 4.5,
    reviews: 1120,
    volatility: "High",
    maxWin: "25,000x",
    rtp: "96.5%",
    minBet: "₱0.10",
    maxBet: "₱50",
    features: ["10 Paylines", "Wild+Scatter Mix", "Grand Jackpot", "RTP Profiles"],
  },
  {
    ...defaults,
    id: "pug-den",
    name: "Pug Den",
    thumb: "/games/pug-den.png",
    category: "slot",
    tag: "New",
    description:
      "1-2-3-4-3-2-1 diamond · 144 connecting ways. Treat Wilds stack multipliers, Treat Yo'Self sticky free spins, and Dawg's Den pooled pot with sticky Toasters. Max win 7,500×.",
    rating: 4.7,
    reviews: 640,
    volatility: "High",
    maxWin: "7,500x",
    rtp: "96.33%",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: [
      "144 Connecting Ways",
      "Diamond 1-2-3-4-3-2-1",
      "Treat Wild Multipliers",
      "Treat Yo'Self",
      "Dawg's Den",
      "Bonus Buy",
    ],
  },
  {
    ...defaults,
    id: "ace-high",
    name: "Ace High",
    thumb: "/games/ace-high.png",
    category: "cards",
    tag: "New",
    description:
      "Classic high-card showdowns with MaxHigh flair. Beat the dealer, climb the ace ladder, and cash big side bets.",
    rating: 4.6,
    reviews: 890,
    volatility: "Medium",
    maxWin: "500x",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["Side Bets", "Ace Ladder", "Perfect Pair", "Fast Deal"],
  },
  {
    ...defaults,
    id: "royal-deal",
    name: "Royal Deal",
    thumb: "/games/royal-deal.png",
    category: "cards",
    tag: "Hot",
    description:
      "A regal poker experience. Chase royal flushes, crown multipliers, and VIP table limits.",
    rating: 4.8,
    reviews: 1540,
    volatility: "High",
    maxWin: "1,000x",
    minBet: "₱2",
    maxBet: "₱1,000",
    features: ["Royal Flush Boost", "Crown Multipliers", "VIP Tables", "Side Pots"],
  },
  {
    ...defaults,
    id: "blackjack-max",
    name: "Blackjack Max",
    thumb: "/games/blackjack-max.png",
    category: "cards",
    description:
      "MaxHigh blackjack with insurance, double-down, and blazing table speed. Perfect 21s pay enhanced odds.",
    rating: 4.7,
    reviews: 3200,
    volatility: "Low",
    maxWin: "3:2",
    minBet: "₱1",
    maxBet: "₱1,000",
    features: ["Insurance", "Double Down", "Split", "Perfect 21 Bonus"],
  },
  {
    ...defaults,
    id: "poker-peak",
    name: "Poker Peak",
    thumb: "/games/poker-peak.png",
    category: "cards",
    tag: "New",
    description:
      "Texas Hold’em energy at MaxHigh. Climb the peak blinds, hit community board boosts, and own the night.",
    rating: 4.6,
    reviews: 1180,
    volatility: "Medium",
    maxWin: "800x",
    minBet: "₱1",
    maxBet: "₱500",
    features: ["Hold’em Boards", "Blind Boosts", "Side Bets", "Peak Jackpot"],
  },
  {
    ...defaults,
    id: "super-ace",
    name: "Super Ace",
    thumb: "/games/super-ace.png",
    category: "slot",
    tag: "Hot",
    provider: "JILI",
    description: "Experience high-octane card action with Super Ace! Golden cards, combo cascades, and massive card multipliers.",
    rating: 4.9,
    reviews: 5410,
    volatility: "Medium",
    maxWin: "1,500x",
    features: ["Golden Cards", "Little & Big Joker", "Combo Multipliers", "Free Spins", "Buy Bonus"],
  },
  {
    ...defaults,
    id: "fortune-gems",
    name: "Fortune Gems",
    thumb: "/games/fortune-gems.png",
    category: "slot",
    tag: "Hot",
    provider: "MaxHigh",
    description:
      "3×3 temple gems with 5 fixed paylines and a dedicated multiplier reel (1×–15×). Extra Bet (EX) raises stake 50% for better multiplier odds. No free spins or bonus rounds.",
    rating: 4.8,
    reviews: 4200,
    // TODO/config-pending — conflicting sources cite 97% / 96.65% / 95.22% floor
    rtp: "97%*",
    volatility: "Medium",
    // TODO/config-pending — 375× single-sourced / unconfirmed
    maxWin: "375x*",
    minBet: "₱0.10",
    maxBet: "₱100",
    features: ["5 Paylines", "Multiplier Reel", "Extra Bet (EX)", "Wild"],
  },

  {
    ...defaults,
    id: "pinata-wins",
    name: "Piñata Wins",
    thumb: "/games/pinata-wins.png",
    category: "slot",
    tag: "New",
    provider: "PG Soft",
    description: "Burst open the festive star piñata for exploding wild frames, coin showers, and high-energy party spins.",
    rating: 4.7,
    reviews: 1950,
    rtp: "96.75%",
    volatility: "Medium",
    maxWin: "5,000x",
    features: ["Gold Framed Symbols", "Exploding Wilds", "Fiesta Free Spins"],
  },
];

export function gamesByCategory(category: GameCategory) {
  return slotGames.filter((g) => g.category === category);
}

export function getGameById(id: string) {
  return slotGames.find((g) => g.id === id);
}
